### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by bartsanchez**

### CODE REVIEW

**Comment by bartsanchez** [comment]
The execution time for the tests is reduced from ~4 minutes to ~60 seconds in my laptop (using 12 workers) and ~120 seconds in the CI (Github), using 4 workers.

However, the following tests is not very parallel-friendly: https://github.com/boriel-basic/zxbasic/blob/main/tests/functional/test_basic.py#L19

Maybe you could find a way of improving it.

**Comment by bartsanchez** [comment]
Also, notice that the following test case is employing ~40 seconds: https://github.com/boriel-basic/zxbasic/blob/main/tests/functional/test_errmsg.txt

**Comment by bartsanchez** [comment]
I've grouped all the `test_basic` tests to run in the same worker. Now there is no race condition and the tests are passing.

**Comment by boriel** [comment]
> Also, notice that the following test case is employing ~40 seconds: https://github.com/boriel-basic/zxbasic/blob/main/tests/functional/test_errmsg.txt

These are, in fact many tests in a single file. It's a doctest.
Don´t know how to make pytest to diferentiate each test case.

**Comment by boriel** [comment]
Bear in mind that coverage measure is expensive.

Prior to adding coverage, running all tests sequentially took < 2 minutes.
Now they take 6mins (x3 times longer!). I wasn't aware of this. Otherwise, a `poe test-without-coverage` action should be added to be run locally.

**Comment by boriel** [comment]
Apparently in some cases coverage poor performance can be improved: https://github.com/pytest-dev/pytest-cov/issues/159
Also, latest pytest-cov is 5.x. Is it available for Python 3.10?

**Pull request merged**
